### ISSUE TITLE
Negative Look Ahead Match

### ISSUE THREAD

**Issue by dtothefp** [axtgr/wildcard-match#4]
Hi I'm trying to get a negative lookahead working but not sure if it's possible in this lib? I'm using it as part of

https://github.com/Escape-Technologies/mookme/issues/59#issuecomment-1509328215

```js
const matcher = require('wildcard-match');

const globs = [
  '**/*.jsx',
  '**/*.js',
  '(?!dont-match/)/**/*',
];
const match = matcher(globs)

console.log(match.regexp)

// /^(?:^(?:[^/\\]*?[/\\]+?)*?[^/\\]*?\.jsx[/\\]*?$|^(?:[^/\\]*?[/\\]+?)*?[^/\\]*?\.js[/\\]*?$|^\([^/\\]!dont\-match[/\\]+?\)[/\\]+?(?:[^/\\]*?[/\\]+?)*?[^/\\]*?[/\\]*?$)$/
```

**Comment by axtgr** [comment]
Hi!

This library doesn't support negation. Its purpose is to be as small and as fast as possible while supporting only the most basic glob features. 

I have a more feature-packed library that has negation: [outmatch](https://github.com/axtgr/outmatch). But note that the syntax is different to yours because lookahead is a feature of regexps, not globs.
